name: tech_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.2
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  flutter_quill: ^11.0.0
  flutter_quill_extensions: ^11.0.0
  flutter_svg: ^2.0.17
  equatable: ^2.0.7
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.4
  http: ^1.3.0
  pin_code_fields: ^8.0.1
  url_launcher: ^6.3.1
  flutter_secure_storage: ^9.2.4
  fl_chart: ^0.66.0
  permission_handler: ^10.4.0
  flutter_launcher_icons: ^0.13.1
  easy_localization: ^3.0.7+1
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  uuid: ^4.5.1
  flutter_slidable: ^3.1.2
  file_picker: ^10.1.7
  pusher_channels_flutter: ^2.4.0
  fluttertoast: ^8.2.12
  audioplayers: ^6.4.0
  pretty_http_logger: ^1.0.5
  firebase_messaging: ^15.2.6
  firebase_core: ^3.13.1
  flutter_localization: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/avatar.png
    - assets/icons/Group.png
    - assets/icons/formal.jpg
    - assets/sounds/notifications.wav
    - assets/translations/en.json
    - assets/translations/ar.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/Group.png"
  android_background_color: "#051754"
  ios_background_color: "#051754"
